name = "project"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
account_id = "a0f0622b36d5e55324b4a3ee91ab6708"

[[d1_databases]]
binding = "DB"
database_name = "D1-DB"
database_id = "c0291228-cc47-4294-904e-4a3995ead6e2"

[[kv_namespaces]]
binding = "CACHE"
id = "6b9b5672375e426dbfc5401a879a5c24"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-bucket"