-- Migration number: 0001 	 2024-07-07T05:35:45.281Z

DROP TABLE IF EXISTS CATS;
CREATE TABLE cats(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER NOT NULL,
    breed TEXT NOT NULL
);